Update .travis.yml
ERROR: file not found: two-fet/two_fer_test.py
The command "pytest --cov-report term-missing --cov=two-fer two-fet/two_fer_test.py" exited with 4.